application: format-link
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: static/images
- url: /binary
  static_dir: static/binary
  mime_type: application/octet-stream
- url: /xml
  static_dir: static/xml
  mime_type: text/xml
- url: .*
  static_files: static/index.html
  upload: static/.*\.html
